package com.wiik_wq.techguns.common.content;

import java.util.List;
import java.util.Map;
import java.util.Set;

public final class TGItemCatalog {

    public static final List<String> HANDHELD_ITEMS = List.of(
            "combatknife",
            "crowbar"
    );

    public static final List<String> GUN_ITEMS = List.of(
            "handcannon",
            "sawedoff",
            "revolver",
            "ak47",
            "m4",
            "thompson",
            "pistol",
            "lmg",
            "boltaction",
            "flamethrower",
            "biogun",
            "rocketlauncher",
            "minigun",
            "combatshotgun",
            "grimreaper",
            "pdw",
            "as50",
            "teslagun",
            "m4_infiltrator",
            "goldenrevolver",
            "pulserifle",
            "lasergun",
            "alienblaster",
            "netherblaster",
            "blasterrifle",
            "powerhammer",
            "grenadelauncher",
            "aug",
            "sonicshotgun",
            "chainsaw",
            "scatterbeamrifle",
            "nucleardeathray",
            "mac10",
            "mibgun",
            "scar",
            "vector",
            "gaussrifle",
            "guidedmissilelauncher",
            "miningdrill",
            "tfg",
            "laserpistol",
            "shishkebap",
            "stielgranate",
            "fraggrenade"
    );

    public static final List<String> SHIELD_ITEMS = List.of(
            "riot_shield",
            "ballistic_shield",
            "advanced_shield"
    );

    public static final List<String> ARMOR_ITEMS = List.of(
            "t1_combat_helmet",
            "t1_combat_chestplate",
            "t1_combat_leggings",
            "t1_combat_boots",
            "t1_scout_helmet",
            "t1_scout_chestplate",
            "t1_scout_leggings",
            "t1_scout_boots",
            "t1_miner_helmet",
            "t1_miner_chestplate",
            "t1_miner_leggings",
            "t1_miner_boots",
            "steam_helmet",
            "steam_chestplate",
            "steam_leggings",
            "steam_boots",
            "hazmat_helmet",
            "hazmat_chestplate",
            "hazmat_leggings",
            "hazmat_boots",
            "t2_combat_helmet",
            "t2_combat_chestplate",
            "t2_combat_leggings",
            "t2_combat_boots",
            "t2_commando_helmet",
            "t2_commando_chestplate",
            "t2_commando_leggings",
            "t2_commando_boots",
            "t2_riot_helmet",
            "t2_riot_chestplate",
            "t2_riot_leggings",
            "t2_riot_boots",
            "t3_combat_helmet",
            "t3_combat_chestplate",
            "t3_combat_leggings",
            "t3_combat_boots",
            "t3_power_helmet",
            "t3_power_chestplate",
            "t3_power_leggings",
            "t3_power_boots",
            "t3_miner_helmet",
            "t3_miner_chestplate",
            "t3_miner_leggings",
            "t3_miner_boots",
            "t3_exo_helmet",
            "t3_exo_chestplate",
            "t3_exo_leggings",
            "t3_exo_boots",
            "t2_beret",
            "t4_praetor_helmet",
            "t4_praetor_chestplate",
            "t4_praetor_leggings",
            "t4_praetor_boots",
            "t4_power_helmet",
            "t4_power_chestplate",
            "t4_power_leggings",
            "t4_power_boots"
    );

    public static final List<String> SIMPLE_ITEMS = List.of(
            "stonebullets",
            "pistolrounds",
            "shotgunrounds",
            "riflerounds",
            "sniperrounds",
            "40mmgrenade",
            "advancedrounds",
            "rocket",
            "rifleroundsstack",
            "smgmagazine",
            "smgmagazineempty",
            "pistolmagazine",
            "pistolmagazineempty",
            "assaultriflemagazine",
            "assaultriflemagazineempty",
            "lmgmagazine",
            "lmgmagazineempty",
            "minigundrum",
            "minigundrumempty",
            "as50magazine",
            "as50magazineempty",
            "advancedmagazine",
            "advancedmagazineempty",
            "compressedairtank",
            "compressedairtankempty",
            "biotank",
            "biotankempty",
            "fueltank",
            "fueltankempty",
            "energycell",
            "energycellempty",
            "nuclearpowercell",
            "nuclearpowercelldepleted",
            "ironreceiver",
            "steelreceiver",
            "obsidiansteelreceiver",
            "carbonreceiver",
            "stonebarrel",
            "ironbarrel",
            "steelbarrel",
            "obsidiansteelbarrel",
            "carbonbarrel",
            "laserbarrel",
            "woodstock",
            "plasticstock",
            "carbonstock",
            "steamarmorplate",
            "plateiron",
            "platecopper",
            "platetin",
            "platebronze",
            "platesteel",
            "plateobsidiansteel",
            "platelead",
            "platecarbon",
            "platetitanium",
            "plasticsheet",
            "rubberbar",
            "mechanicalpartsiron",
            "mechanicalpartsobsidiansteel",
            "mechanicalpartscarbon",
            "heavycloth",
            "biomass",
            "copperwire",
            "goldwire",
            "carbonfibers",
            "circuitboard",
            "circuitboardelite",
            "powerplating",
            "coil",
            "cyberneticparts",
            "electricengine",
            "laserfocus",
            "pumpmechanism",
            "rademitter",
            "sonicemitter",
            "tgx",
            "nethercharge",
            "treatedleather",
            "oretitanium",
            "ingotcopper",
            "ingottin",
            "ingotbronze",
            "ingotlead",
            "ingotsteel",
            "ingotobsidiansteel",
            "ingottitanium",
            "nuggetcopper",
            "nuggetlead",
            "nuggetsteel",
            "gasmaskfilter",
            "gliderbackpack",
            "gliderwing",
            "antigravcore",
            "oxygenmask",
            "machinestackupgrade",
            "rawrubber",
            "rawplastic",
            "yellowcake",
            "enricheduranium",
            "turretarmoriron",
            "turretarmorsteel",
            "turretarmorobsidiansteel",
            "turretarmorcarbon",
            "quartzrod",
            "rcheatray",
            "rcuvemitter",
            "shotgunrounds_incendiary",
            "as50magazine_incendiary",
            "sniperrounds_incendiary",
            "pistolrounds_incendiary",
            "riflerounds_incendiary",
            "rifleroundsstack_incendiary",
            "smgmagazine_incendiary",
            "pistolmagazine_incendiary",
            "minigundrum_incendiary",
            "assaultriflemagazine_incendiary",
            "lmgmagazine_incendiary",
            "rocket_nuke",
            "tacticalnukewarhead",
            "miningdrillhead_obsidian",
            "miningdrillhead_carbon",
            "powerhammerhead_obsidian",
            "powerhammerhead_carbon",
            "chainsawblades_obsidian",
            "chainsawblades_carbon",
            "redstone_battery",
            "redstone_battery_empty",
            "gaussrifleslugs",
            "gaussbarrel",
            "shieldedtitaniumbarrel",
            "titaniumreceiver",
            "plasmagenerator",
            "workinggloves",
            "protectivefiber",
            "oredrillsmall_steel",
            "oredrillsmall_obsidiansteel",
            "oredrillsmall_carbon",
            "oredrillmedium_steel",
            "oredrillmedium_obsidiansteel",
            "oredrillmedium_carbon",
            "oredrilllarge_steel",
            "oredrilllarge_obsidiansteel",
            "oredrilllarge_carbon",
            "as50magazine_explosive",
            "sniperrounds_explosive",
            "rocket_high_velocity",
            "infusionbag",
            "upgrade_protection_1",
            "upgrade_projectile_protection_1",
            "upgrade_blast_protection_1",
            "upgrade_protection_2",
            "upgrade_projectile_protection_2",
            "upgrade_blast_protection_2",
            "upgrade_protection_3",
            "upgrade_projectile_protection_3",
            "upgrade_blast_protection_3",
            "radaway",
            "radpills",
            "gasmask",
            "glider",
            "jumppack",
            "scubatanks",
            "nightvisiongoggles",
            "jetpack",
            "tacticalmask",
            "antigravpack",
            "worldgentesttool",
            "buildingscantool"
    );

    public static final Map<String, String> GUN_TEXTURES = Map.ofEntries(
            Map.entry("handcannon", "handgun"),
            Map.entry("sawedoff", "sawedoff"),
            Map.entry("revolver", "revolver"),
            Map.entry("ak47", "ak47texture"),
            Map.entry("m4", "m4texture"),
            Map.entry("thompson", "thompson"),
            Map.entry("pistol", "pistol3"),
            Map.entry("lmg", "mg2_texture"),
            Map.entry("boltaction", "boltactionrifle"),
            Map.entry("flamethrower", "flamethrower"),
            Map.entry("biogun", "biogun"),
            Map.entry("rocketlauncher", "rocketlauncher"),
            Map.entry("minigun", "minigun"),
            Map.entry("combatshotgun", "combatshotgun"),
            Map.entry("grimreaper", "grimreaper"),
            Map.entry("pdw", "pdw"),
            Map.entry("as50", "as50texture"),
            Map.entry("teslagun", "teslagun"),
            Map.entry("m4_infiltrator", "m4_uq_texture"),
            Map.entry("goldenrevolver", "goldenrevolver"),
            Map.entry("pulserifle", "pulserifle"),
            Map.entry("lasergun", "lasergun"),
            Map.entry("alienblaster", "alien_blaster"),
            Map.entry("netherblaster", "cyberdemonblaster"),
            Map.entry("blasterrifle", "blasterrifle"),
            Map.entry("powerhammer", "powerhammer"),
            Map.entry("grenadelauncher", "grenadelauncher"),
            Map.entry("aug", "augtexture"),
            Map.entry("sonicshotgun", "sonicshotgun"),
            Map.entry("chainsaw", "chainsaw"),
            Map.entry("scatterbeamrifle", "lasergunnew"),
            Map.entry("nucleardeathray", "ndr"),
            Map.entry("mac10", "mac10texture"),
            Map.entry("mibgun", "mibgun"),
            Map.entry("scar", "scar_texture"),
            Map.entry("vector", "vector_texture"),
            Map.entry("gaussrifle", "gaussrifle"),
            Map.entry("guidedmissilelauncher", "guidedmissilelauncher"),
            Map.entry("miningdrill", "miningdrill_obsidian"),
            Map.entry("tfg", "tfg"),
            Map.entry("laserpistol", "laser_pistol"),
            Map.entry("shishkebap", "shishkebab_texture"),
            Map.entry("stielgranate", "stielgranate"),
            Map.entry("fraggrenade", "frag_grenade_texture")
    );

    public static final Map<String, String> TEXTURE_FALLBACKS = Map.ofEntries(
            Map.entry("as50magazine", "guns/as50_mag"),
            Map.entry("as50magazine_explosive", "guns/as50_mag_exp"),
            Map.entry("as50magazine_incendiary", "guns/as50_mag_inc"),
            Map.entry("as50magazineempty", "guns/as50_mag"),
            Map.entry("assaultriflemagazine", "guns/ar_mag"),
            Map.entry("assaultriflemagazine_incendiary", "guns/ar_mag_inc"),
            Map.entry("assaultriflemagazineempty", "guns/ar_mag"),
            Map.entry("lmgmagazine", "guns/lmg_mag"),
            Map.entry("lmgmagazine_incendiary", "guns/lmg_mag_inc"),
            Map.entry("lmgmagazineempty", "guns/lmg_mag"),
            Map.entry("rocket_high_velocity", "guns/rocket_hv"),
            Map.entry("steam_helmet", "models/armor/steam_armor"),
            Map.entry("steam_chestplate", "models/armor/steam_armor"),
            Map.entry("steam_leggings", "models/armor/steam_armor"),
            Map.entry("steam_boots", "models/armor/steam_armor"),
            Map.entry("t3_power_helmet", "models/armor/powerarmor"),
            Map.entry("t3_power_chestplate", "models/armor/powerarmor"),
            Map.entry("t3_power_leggings", "models/armor/powerarmor"),
            Map.entry("t3_power_boots", "models/armor/powerarmor"),
            Map.entry("t4_power_helmet", "models/armor/powerarmor_mk2"),
            Map.entry("t4_power_chestplate", "models/armor/powerarmor_mk2"),
            Map.entry("t4_power_leggings", "models/armor/powerarmor_mk2"),
            Map.entry("t4_power_boots", "models/armor/powerarmor_mk2"),
            Map.entry("steelbarrel", "items/ironbarrel")
    );

    public static final Set<String> LEGACY_GUN_RENDER_ITEMS = Set.of(
            "m4",
            "ak47",
            "lmg",
            "handcannon",
            "sawedoff",
            "thompson",
            "boltaction",
            "biogun",
            "flamethrower",
            "pistol",
            "rocketlauncher",
            "minigun",
            "combatshotgun",
            "revolver",
            "grimreaper",
            "pdw",
            "as50",
            "m4_infiltrator",
            "goldenrevolver",
            "pulserifle",
            "teslagun",
            "netherblaster",
            "lasergun",
            "alienblaster",
            "blasterrifle",
            "powerhammer",
            "aug",
            "sonicshotgun",
            "chainsaw",
            "scatterbeamrifle",
            "nucleardeathray",
            "scar",
            "vector",
            "mac10",
            "mibgun",
            "gaussrifle",
            "grenadelauncher",
            "guidedmissilelauncher",
            "miningdrill",
            "tfg",
            "laserpistol",
            "shishkebap",
            "stielgranate",
            "fraggrenade"
    );

    public static final Set<String> LEGACY_ITEM_RENDER_ITEMS = Set.of(
            "assaultriflemagazine",
            "assaultriflemagazineempty",
            "assaultriflemagazine_incendiary",
            "lmgmagazine",
            "lmgmagazineempty",
            "lmgmagazine_incendiary",
            "as50magazine",
            "as50magazineempty",
            "as50magazine_incendiary",
            "as50magazine_explosive",
            "rocket",
            "rocket_nuke",
            "rocket_high_velocity",
            "riot_shield",
            "ballistic_shield",
            "advanced_shield"
    );

    public static final Set<String> ARMOR_PREVIEW_RENDER_ITEMS = Set.of(
            "steam_helmet",
            "steam_chestplate",
            "steam_leggings",
            "steam_boots",
            "t3_power_helmet",
            "t3_power_chestplate",
            "t3_power_leggings",
            "t3_power_boots",
            "t4_power_helmet",
            "t4_power_chestplate",
            "t4_power_leggings",
            "t4_power_boots"
    );

    public static final Set<String> OBJ_MODEL_ITEMS = Set.of(
            "gaussrifle",
            "grenadelauncher"
    );

    public static final Set<String> GUNS_WITHOUT_BOW_ARM_POSE = Set.of(
            "shishkebap"
    );

    public static boolean usesSpecialItemRenderer(String id) {
        return LEGACY_GUN_RENDER_ITEMS.contains(id)
                || LEGACY_ITEM_RENDER_ITEMS.contains(id)
                || ARMOR_PREVIEW_RENDER_ITEMS.contains(id);
    }

    public static boolean usesObjItemModel(String id) {
        return OBJ_MODEL_ITEMS.contains(id);
    }

    public static boolean usesBowArmPose(String id) {
        return GUN_ITEMS.contains(id) && !GUNS_WITHOUT_BOW_ARM_POSE.contains(id);
    }

    private TGItemCatalog() {
    }
}
